<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite3bd23231d68c236a4357ec1128a2f01
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'SquareConnect\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'SquareConnect\\' => 
        array (
            0 => __DIR__ . '/..' . '/square/connect/lib',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite3bd23231d68c236a4357ec1128a2f01::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite3bd23231d68c236a4357ec1128a2f01::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
